// <auto-generated />
namespace ProvaBackEnd.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _float : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_float));
        
        string IMigrationMetadata.Id
        {
            get { return "201911132150420_float"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
